// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bestStat': string;
  'comboCount': string;
  'factorCombo': string;
  'header': string;
  'headerDivider': string;
  'inlineIcon': string;
  'itemTriagePane': string;
  'junkIcon': string;
  'keepIcon': string;
  'keepMeter': string;
  'tagIcon': string;
  'thisStat': string;
  'triageTable': string;
}
export const cssExports: CssExports;
export default cssExports;
