// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inlineIcon': string;
  'itemTriagePane': string;
}
export const cssExports: CssExports;
export default cssExports;
